"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NameRegistry__factory = exports.NamePriceOracle__factory = exports.NameController__factory = exports.IResolver__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IResolver__factory_1 = require("./IResolver__factory");
Object.defineProperty(exports, "IResolver__factory", { enumerable: true, get: function () { return IResolver__factory_1.IResolver__factory; } });
var NameController__factory_1 = require("./NameController__factory");
Object.defineProperty(exports, "NameController__factory", { enumerable: true, get: function () { return NameController__factory_1.NameController__factory; } });
var NamePriceOracle__factory_1 = require("./NamePriceOracle__factory");
Object.defineProperty(exports, "NamePriceOracle__factory", { enumerable: true, get: function () { return NamePriceOracle__factory_1.NamePriceOracle__factory; } });
var NameRegistry__factory_1 = require("./NameRegistry__factory");
Object.defineProperty(exports, "NameRegistry__factory", { enumerable: true, get: function () { return NameRegistry__factory_1.NameRegistry__factory; } });
